- name: configure vm 
  hosts: azure-vm
  remote_user: farouk
  tasks:
  - name: Creation folder/ansible_flask
    file:
      path: /home/farouk/ansible_flask
      state: touch
  - name: copy file
    copy:
      src: /Users/farouk/Documents/simplon/david/ansible_flask
      dest: /home/farouk/ansible_flask

  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: Install PostgreSQL
  apt: name={{ item }} update_cache=true state=installed
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2
  tags: packages

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: Ensure database is created
  sudo_user: user
  postgresql_db: name=ansible_data 
             encoding='UTF-8'
             lc_collate='en_US.UTF-8'
             lc_ctype='en_US.UTF-8'
             template='template0'
             state=present

- name: Ensure user has access to the database
  sudo_user: postgres
  postgresql_user: db=ansible_data
               name=user
               password=pwd123
               priv=ALL
               state=present
