- name: configure vm 
  hosts: azure-vm
  become: yes
  become_method: sudo
  remote_user: farouk
  tasks:
    # - name: Creation folder/ansible_flask
    #   file:
    #     path: /home/farouk/ansible_flask 
    #     state: directory
    #     mode: '0755'
    # - name: copy file
    #   copy:
    #     src: /Users/farouk/Documents/simplon/david/ansible_flask
    #     dest: /home/farouk/
    # - apt:
    #     name: postgresql
    #     state: latest
    # - name: ensure packages are installed
      # apt: 
      #   name: ['libpq-dev', 'python-psycopg2', 'python-pip', 'python-dev', 'python3-pip', 'python3-dev', 'python3.8']
      # pip:
      #   # name: psycopg2
      #   # executable: pip3
      #   name: python-dotenv
      #   executable: pip3
    - name: Create user psql
      become: yes
      become_user: postgres
      postgresql_user:
        name: "test"
        password: "pw123"
        role_attr_flags: "CREATEDB,NOSUPERUSER"
    - name: Create database
      become: yes
      become_user: postgres
      postgresql_db:
          name: "dbtest"
          owner: "postgres"
    - name: Execute script database
      command: python3 /home/farouk/ansible_flask/db.py
    - name: Execute script app.py
      command: python3 /home/farouk/ansible_flask/app.py

     
    
    
    
        
 